/**
 * @file AstarMMmvt.hpp
 * Generated by VisibleSim BlockCode Generator
 * https://services-stgi.pu-pm.univ-fcomte.fr/visiblesim/generator.php#
 * @author yourName
 * @date 2000-12-02                                                                     
 **/

#ifndef mvtMessages_H_
#define mvtMessages_H_

#include "comm/network.h"
#include "grid/cell3DPosition.h"
#include "robots/catoms3D/catoms3DBlockCode.h"
#include "utils/color.h"
#include <map>

static const uint MSG_DELAY = 0;

using namespace Catoms3D;

class FPCheckMessage : public HandleableMessage {
    protected:
        std::map<Cell3DPosition, std::vector<Cell3DPosition>> neighGraph;
        Cell3DPosition senderPos;
        
    public:
        FPCheckMessage(const Cell3DPosition& sPos, std::map<Cell3DPosition, std::vector<Cell3DPosition>> nG)
            : HandleableMessage(), neighGraph(nG), senderPos(sPos) {};
        
        virtual ~FPCheckMessage(){};
        
        virtual void handle(BaseSimulator::BlockCode* bc) override;
        virtual Message* clone() const override {return new FPCheckMessage(*this);}
        virtual std::string getName() const override { return "FPCheckMessage"; }
};

#endif